hello/urls.py
from unicodedata import name
from django import views
from django.urls import path
from . import views 

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.greet, name="greet")
]

hobbies/urls.py
import imp
from django.urls import path
from . import views
import hobbies

app_name = "hobbies"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

lecture3/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
    path('newyear/', include('newyear.urls')),
    path('tasks/', include('tasks.urls')),
    path('hobbies/', include('hobbies.urls'))
]

newyear/urls.py
from unicodedata import name
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index")
]

tasks/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name= "index"),
    path("add", views.add, name="add")
]

hobbies/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def greet(request, name):
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    })

hobbies/views.py
from django.urls import reverse
from http.client import HTTPResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django import forms
import hobbies
# Create your views here.

# Generate form elements
class NewHobbiesForm(forms.Form):
    hobby = forms.CharField(label="New Hobby:")

def index(request):
    if not "hobbies" in request.session:
        request.session["hobbies"] = []     
    return render(request, "hobbies/index.html", {
        "hobbies":request.session["hobbies"]
    })

def add(request):
    if request.method == "POST":
        form = NewHobbiesForm(request.POST)
        if form.is_valid():
            hobby = form.cleaned_data["hobby"]
            request.session["hobbies"] += [hobby]
            return HttpResponseRedirect(reverse("hobbies:index"))
        else:
            return render(request, "hobbies/add.html", {
                "form":form
            })
    return render(request, "hobbies/add.html", {
        "form": NewHobbiesForm()
    })      

newyear/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def index(request):
    now =datetime.datetime.now()
    newyear = now.month == 1 and now.day == 1
    return render(request, "newyear/index.html", {
        "newyear": newyear
    })

tasks/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django import forms
from django.urls import reverse

import tasks

# Create your views here.

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
    

def index(request):
    if not "tasks" in request.session:
        request.session["tasks"] = []
    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add.html", {
                "form":form
            })
    return render(request, "tasks/add.html", {
        "form":NewTaskForm()
    })

hello/templates/hello/greet.html
.html5 <!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Greet</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <h1>Hello, {{ name }}</h1>
        <script src="" async defer></script>
    </body>
</html>

hello/templates/hello/index.html
.<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Hello App</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <h1>Hello, World!</h1>
        
        <script src="" async defer></script>
    </body>
</html>

hobbies/templates/hobbies/add.html
{% extends "hobbies/layout.html" %}
{% block body %}
        <h1>Add Hobbies</h1>
        <form action="{% url 'hobbies:add' %}" method="post"> 
            {% csrf_token %}
            {{ form }}
            <input type="submit">
        </form>
        <a href="{% url 'hobbies:index' %}">View Hobbies</a>
{% endblock %}

hobbies/templates/hobbies/index.html
{% extends "hobbies/layout.html" %}
{% block body %}
        <h1>My Hobbies</h1>
        <ul>
            {% for hobby in hobbies %}
                <li>{{ hobby }}</li>
                {% empty %}
                <h1>No hobby!</h1>
            {% endfor %}
        </ul>
        <a href="{% url 'hobbies:add' %}">Add new hobby.</a>
{% endblock %}

hobbies/templates/hobbies/layout.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>hobbies layout</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        {% block body %}
        {% endblock %}
        <script src="" async defer></script>
    </body>
</html>

newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>newyear app</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'newyear/styles.css' %}">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        {% if newyear %}
            <h1>YES</h1>
        {% else %}
            <h1>NO</h1>
        {% endif %}
        <script src="" async defer></script>
    </body>
</html>

tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}
{% block body %}
<h1>Add Task</h1>
<form action="{% url 'tasks:add' %}" method="post">
    <!-- security token -->
    {% csrf_token %}
    <!--plug in a form with django-->
   {{ form }}
    <input type="submit">
</form>
<a href="{% url 'tasks:index' %}">View Tasks</a>
{% endblock %}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}
{% block body %}
<h1>Tasks</h1>
        <ul>
            {% for task in tasks %}
                <li>{{ task }}</li>
            {% empty %}
                <h1>No task.</h1>
            {% endfor %}
        </ul>
        <a href="{% url 'tasks:add' %}">Add a New Task</a>
{% endblock %}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        
        {% block body %}
        {% endblock %}

        <script src="" async defer></script>
    </body>
</html>